{{- if $.Values.secrets }}
{{- range $id, $secret := $.Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $secret.name $ | trunc 63 | trimSuffix "-" | trimSuffix "." | quote }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "metadata.labels" $ | nindent 4 }}
type: {{ tpl ( default "Opaque" $secret.type ) $ | quote }}
data:
  {{- range $key, $value := $secret.content }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}